apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-nginx
  template:
    metadata:
      labels:
        app: angular-nginx
    spec:
      containers:
      - name: angular-nginx
        image: enriqueav99/angular:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: angular-nginx
  namespace: default

spec:
  selector:
    app: angular-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
